//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /dataa/home/joha/src/csharp/crawl/src/libcompiler/Crawl.g4 by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace libcompiler.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICrawlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public partial class CrawlBaseListener : ICrawlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTranslation_unit([NotNull] CrawlParser.Translation_unitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTranslation_unit([NotNull] CrawlParser.Translation_unitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.import_directives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_directives([NotNull] CrawlParser.Import_directivesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.import_directives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_directives([NotNull] CrawlParser.Import_directivesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.import_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_directive([NotNull] CrawlParser.Import_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.import_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_directive([NotNull] CrawlParser.Import_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] CrawlParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] CrawlParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.side_effect_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSide_effect_stmt([NotNull] CrawlParser.Side_effect_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.side_effect_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSide_effect_stmt([NotNull] CrawlParser.Side_effect_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.if_selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_selection([NotNull] CrawlParser.If_selectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.if_selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_selection([NotNull] CrawlParser.If_selectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.for_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_loop([NotNull] CrawlParser.For_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.for_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_loop([NotNull] CrawlParser.For_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.while_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_loop([NotNull] CrawlParser.While_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.while_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_loop([NotNull] CrawlParser.While_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] CrawlParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] CrawlParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] CrawlParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] CrawlParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.function_decleration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_decleration([NotNull] CrawlParser.Function_declerationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.function_decleration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_decleration([NotNull] CrawlParser.Function_declerationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] CrawlParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] CrawlParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] CrawlParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] CrawlParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.generic_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_parameters([NotNull] CrawlParser.Generic_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.generic_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_parameters([NotNull] CrawlParser.Generic_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.generic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric([NotNull] CrawlParser.GenericContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.generic"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric([NotNull] CrawlParser.GenericContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.variable_declerations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declerations([NotNull] CrawlParser.Variable_declerationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.variable_declerations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declerations([NotNull] CrawlParser.Variable_declerationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.variable_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_decl([NotNull] CrawlParser.Variable_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.variable_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_decl([NotNull] CrawlParser.Variable_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_body([NotNull] CrawlParser.Function_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_body([NotNull] CrawlParser.Function_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.class_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_declaration([NotNull] CrawlParser.Class_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.class_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_declaration([NotNull] CrawlParser.Class_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.inheritances"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInheritances([NotNull] CrawlParser.InheritancesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.inheritances"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInheritances([NotNull] CrawlParser.InheritancesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.inheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInheritance([NotNull] CrawlParser.InheritanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.inheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInheritance([NotNull] CrawlParser.InheritanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.class_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_body([NotNull] CrawlParser.Class_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.class_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_body([NotNull] CrawlParser.Class_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] CrawlParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] CrawlParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] CrawlParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] CrawlParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_type([NotNull] CrawlParser.Array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_type([NotNull] CrawlParser.Array_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.function_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_type([NotNull] CrawlParser.Function_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.function_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_type([NotNull] CrawlParser.Function_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.function_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_arguments([NotNull] CrawlParser.Function_argumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.function_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_arguments([NotNull] CrawlParser.Function_argumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.protection_level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtection_level([NotNull] CrawlParser.Protection_levelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.protection_level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtection_level([NotNull] CrawlParser.Protection_levelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.ref_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRef_expression_list([NotNull] CrawlParser.Ref_expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.ref_expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRef_expression_list([NotNull] CrawlParser.Ref_expression_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_list([NotNull] CrawlParser.Expression_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.expression_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_list([NotNull] CrawlParser.Expression_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CrawlParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CrawlParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.range_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange_expression([NotNull] CrawlParser.Range_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.range_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange_expression([NotNull] CrawlParser.Range_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_expression([NotNull] CrawlParser.Or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_expression([NotNull] CrawlParser.Or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expression([NotNull] CrawlParser.And_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expression([NotNull] CrawlParser.And_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.comparison_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_expression([NotNull] CrawlParser.Comparison_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.comparison_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_expression([NotNull] CrawlParser.Comparison_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditive_expression([NotNull] CrawlParser.Additive_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.additive_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditive_expression([NotNull] CrawlParser.Additive_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicative_expression([NotNull] CrawlParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.multiplicative_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicative_expression([NotNull] CrawlParser.Multiplicative_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.exponential_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponential_expression([NotNull] CrawlParser.Exponential_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.exponential_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponential_expression([NotNull] CrawlParser.Exponential_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCast_expression([NotNull] CrawlParser.Cast_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCast_expression([NotNull] CrawlParser.Cast_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expression([NotNull] CrawlParser.Unary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expression([NotNull] CrawlParser.Unary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_expression([NotNull] CrawlParser.Postfix_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_expression([NotNull] CrawlParser.Postfix_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_expression([NotNull] CrawlParser.Call_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_expression([NotNull] CrawlParser.Call_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.subfield_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubfield_expression([NotNull] CrawlParser.Subfield_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.subfield_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubfield_expression([NotNull] CrawlParser.Subfield_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.index_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_expression([NotNull] CrawlParser.Index_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.index_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_expression([NotNull] CrawlParser.Index_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.generic_unpack_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_unpack_expression([NotNull] CrawlParser.Generic_unpack_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.generic_unpack_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_unpack_expression([NotNull] CrawlParser.Generic_unpack_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] CrawlParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] CrawlParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.comparison_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_symbol([NotNull] CrawlParser.Comparison_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.comparison_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_symbol([NotNull] CrawlParser.Comparison_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.unary_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_symbol([NotNull] CrawlParser.Unary_symbolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.unary_symbol"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_symbol([NotNull] CrawlParser.Unary_symbolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] CrawlParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] CrawlParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean_literal([NotNull] CrawlParser.Boolean_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.boolean_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean_literal([NotNull] CrawlParser.Boolean_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.integer_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger_literal([NotNull] CrawlParser.Integer_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.integer_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger_literal([NotNull] CrawlParser.Integer_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.real_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReal_literal([NotNull] CrawlParser.Real_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.real_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReal_literal([NotNull] CrawlParser.Real_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CrawlParser.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_literal([NotNull] CrawlParser.String_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CrawlParser.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_literal([NotNull] CrawlParser.String_literalContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace libcompiler.Parser
